### ISSUE TITLE
Migration to play 2.4

### ISSUE THREAD

**Issue by lavrov** [mumoshu/play2-memcached#32]
Play plugins will be deprecated in play 2.4

**Comment by mkurz** [comment]
@mumoshu Could you please upgrade the play2-memcached plugin to support Play `2.4.0-RC2` and provide a Snapshots or release candidate with Play 2.4 support? Thanks!

**Comment by manuelbernhardt** [comment]
+1

Play is now in RC5, I think we'll see a release soon. It would be great to have the plugin supported in 2.4 as well.

**Comment by mkurz** [comment]
@mumoshu Play 2.4 has been released (https://groups.google.com/forum/?fromgroups#!topic/play-framework/gXYhA-BiSqk)! Could you please release a new, compatible version of play2-memcached as well? Thanks!

**Comment by mumoshu** [comment]
Hi,

[I'm already working on the play-2.4 branch](https://github.com/mumoshu/play2-memcached/tree/play-2.4) and I will release a new version this weekend :smile:

**Comment by mkurz** [comment]
@mumoshu Awesome, thanks!

**Comment by lloydmeta** [comment]
:+1:

**Comment by anand-singh** [comment]
+1

**Comment by anand-singh** [comment]
@mumoshu :  Any luck with Play 2.4 release. Thanks

**Comment by mumoshu** [comment]
@lavrov @mkurz @manuelbernhardt @lloydmeta @anand-singh Thanks for your interest!
I have just published `play2-memcached-play24-0.7.0`. I will soon be available in the central, too.

See [the updated README](https://github.com/mumoshu/play2-memcached#library-dependencies) for the updated library dependency.

Just for your information, the artifact is now named as so because I'm now cross-building play2-memcached against not only multiple scala versions but multiple play versions(2.3.x and 2.4.0).

**Comment by lloydmeta** [comment]
Awesome thanks for the updated release. お疲れ様です。

**Comment by anand-singh** [comment]
@mumoshu awesome, thanks!
